server:
  port: 8007

spring:
  application:
    name: gateway
#  main:
#    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: payment_routh
          uri: http://localhost:8001     #匹配后提供服务的路由地址
          #uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/**         # 断言，路径相匹配的进行路由



